Backport PR #14891
Backports https://github.com/matplotlib/matplotlib/pull/14891

Avoids tracebacks such as:

File "$PREFIX/lib/python3.8/site-packages/matplotlib/axes/_base.py", line 1694, in axis
     self.set_xlim([xlim[0], xlim[0] + edge_size],
File "$PREFIX/lib/python3.8/site-packages/matplotlib/axes/_base.py", line 3270, in set_xlim
     left, right = sorted([left, right], reverse=reverse)
TypeError: only integer scalar arrays can be converted to a scalar index